export const Colors = {
  PRIMARY: {
    PRIMARY_RETRO_BLUE: "#2467EC",
    PRIMARY_QUEER_BLUE: "#8DACEB",
    PRIMARY_HUSKY: "#E1E9FA",
  },
  SECONDARY: {
    SECONDARY_LEMON_WHISPER: "#FFB013",
    SECONDARY_MILK_QUARTZ: "#F5DEB0",
    SECONDARY_BELGIAN_CREAM: "#FAF2E1",
  },
  NEUTRAL: {
    NEUTRAL_DARK_VOID: "#141517",
    NEUTRAL_SHADOW_MOUNTAIN: "#575757",
    NEUTRAL_CENTRE_STAGE: "#C6C7CC",
    NEUTRAL_SPRINGTIME_RAIN: "#EDEEF2",
    NEUTRAL_ZHEN_ZHU_BAI_PEARL: "#F7F7F9",
    NEUTRAL_WHITE: "#FFFFFF",
  },
  ERROR: "#EC2424",
  WARNING: "#FFCB13",
  SUCCESS: "#00C48C",
};

